//
// Created by Andy on 11/18/2018.
//

#ifndef GENETICALGORITHM_GENETICALGORITHN_HPP
#define GENETICALGORITHM_GENETICALGORITHN_HPP


class GeneticAlgorithn {

};


#endif //GENETICALGORITHM_GENETICALGORITHN_HPP
